### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by pennpeng** [raffaelespazzoli/openshift-federation#1]
```
TASK [Gathering Facts] ********************************************************************************************************************************************
task path: /home/openshift-federation/ansible/playbooks/install-federation/install-federation.yaml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1547006035.46-114723135515305 `" && echo ansible-tmp-1547006035.46-114723135515305="` echo /root/.ansible/tmp/ansible-tmp-1547006035.46-114723135515305 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-15663G532_2/tmpU0Z_jN TO /root/.ansible/tmp/ansible-tmp-1547006035.46-114723135515305/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1547006035.46-114723135515305/ /root/.ansible/tmp/ansible-tmp-1547006035.46-114723135515305/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1547006035.46-114723135515305/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1547006035.46-114723135515305/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [install-federation : login to the clusters] *****************************************************************************************************************
task path: /home/openshift-federation/ansible/roles/install-federation/tasks/main.yaml:2
fatal: [localhost]: FAILED! => {
    "msg": "'clusters' is undefined"
}
	to retry, use: --limit @/home/openshift-federation/ansible/playbooks/install-federation/install-federation.retry

PLAY RECAP ********************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   


```

**Comment by pennpeng** [comment]
```
# cat localhosts 
clusters:
- name: caowei
  url: openshift-node-1:8443
  username: admin
  password: 99cloud
  federation_control_plane: true  
- name: penn
  url: 172.50.0.39:8443
  username: admin
  password: admin
  federation_control_plane: false 

```
